### ISSUE TITLE
Bump generator version

### ISSUE THREAD

**Issue by julienma** [Leadformance/generator-bridge-template#9]
@dpellier you should update the package version so devs know which version they currently use: 
https://github.com/Leadformance/generator-bridge-template/blob/master/package.json#L4

**Comment by dpellier** [comment]
In fact it's already updated, at least in the release source code.
I'm surprised that the master is not the same.

Investigation in progress....

**Comment by dpellier** [comment]
OK just the released branch not yet merged onto master
